name: android

on:
  push:
    paths:
    - Dockerfile.android
  pull_request:
    paths:
    - Dockerfile.android

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - uses: docker/setup-buildx-action@v2
    - name: Build container image
      uses: docker/build-push-action@v3
      with:
        file: Dockerfile.android
        tags: ghcr.io/nghttp2/nghttp2
